name: github pages

# :)

on:
  push:
    branches:
    - master
    paths:
    - 'site/**'
    - '.github/workflows/gh-pages.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.68.3'
        extended: true

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir -s site -d public

    - name: Copy project files to public
      run: cp -R project/ ./site/public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site/public
